export const IITK_DEPARTMENT_OPTIONS = [
  { value: 'AE', label: 'Aerospace Engineering (AE)' },
  { value: 'BSBE', label: 'Biological Sciences and Bioengineering (BSBE)' },
  { value: 'CE', label: 'Civil Engineering (CE)' },
  { value: 'CHE', label: 'Chemical Engineering (CHE)' },
  { value: 'CHM', label: 'Chemistry (CHM)' },
  { value: 'COGS', label: 'Cognitive Science (COGS)' },
  { value: 'CSE', label: 'Computer Science and Engineering (CSE)' },
  { value: 'DESIGN', label: 'Design Programme' },
  { value: 'ECO', label: 'Economics / Economic Sciences (ECO)' },
  { value: 'EE', label: 'Electrical Engineering (EE)' },
  { value: 'ES', label: 'Earth Sciences (ES)' },
  { value: 'HSS', label: 'Humanities and Social Sciences (HSS)' },
  { value: 'IME', label: 'Industrial and Management Engineering (IME)' },
  { value: 'ME', label: 'Mechanical Engineering (ME)' },
  { value: 'MSE', label: 'Materials Science and Engineering (MSE)' },
  { value: 'MTH', label: 'Mathematics and Statistics (MTH)' },
  { value: 'PHY', label: 'Physics (PHY)' },
  { value: 'SPS', label: 'Space, Planetary and Astronomical Sciences and Engineering (SPS)' },
];
